# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cclikpi', models.CharField(max_length=20, verbose_name='Bool cclikpi')),
                ('nom', models.CharField(max_length=100, verbose_name='Book nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Book prenom')),
                ('message', models.CharField(max_length=10000, verbose_name='Book message')),
                ('published_time', models.TimeField(blank=True, null=True, verbose_name='Time published')),
            ],
        ),
    ]
