# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_time',
        ),
        migrations.AlterField(
            model_name='book',
            name='cclikpi',
            field=models.CharField(max_length=20, verbose_name='Book cclikpi'),
        ),
    ]
